# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Specify the platform and iOS version
platform :ios, min_ios_version_supported
prepare_react_native_project!

# Configure Flipper (debugging tool)
# Disable Flipper if NO_FLIPPER environment variable is set
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# Check if frameworks should be used
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Define the main target
target 'Biologic' do
  config = use_native_modules! # This loads the native modules

  use_react_native!(
    :path => config[:reactNativePath],
    :flipper_configuration => flipper_config, # Configure Flipper
    :app_path => "#{Pod::Config.instance.installation_root}/.." # Path to the app's root
  )

  # Define permission handlers for iOS (Location)


  # Define a sub-target for tests
  target 'BiologicTests' do
    inherit! :complete
    # Pods for testing
  end

  # Post-install script to ensure everything is correctly linked
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
